### ISSUE TITLE
ImportAndExportCsvFilesSample throw exception

### ISSUE THREAD

**Issue by StevenKung** [EPPlusSoftware/EPPlus.Sample.NetFramework#1]
ImportAndExportCsvFilesSample throw System.ArgumentException: 'Row out of range' exception in line 85.

**Comment by JanKallman** [comment]
I can't reproduce this. In which environment are you running the sample?
Culture Code?

**Comment by StevenKung** [comment]
In Visual Studio 2019 16.5.4
Culture code is "zh-tw"

**Comment by JanKallman** [comment]
I still can't reproduce this. 
Can you supply the full stack trace?

**Comment by StevenKung** [comment]
![image](https://user-images.githubusercontent.com/33179995/79839934-cbe9c280-83e7-11ea-809d-4da24e90cc81.png)

**Comment by JanKallman** [comment]
I can't reproduce this. 
From the error it seems that EPPlus doesen't split the rows on cr/lf. Just to verify, can you check that the Sample5-1.txt file is unchanged (with git diff, if you have cloned the repo)?

**Comment by StevenKung** [comment]
I did not change the content of files.
And the same problem occurs at line 153

**Comment by StevenKung** [comment]
Read the file content and display.
It should be same with your file?
![未命名](https://user-images.githubusercontent.com/33179995/79851695-3f93cb80-83f8-11ea-8925-c09666be4236.png)

**Comment by StevenKung** [comment]
set EOL="\n" of ExcelTextFormat, problem solved and Excel content look good.

**Comment by JanKallman** [comment]
The files should have CR/LF as line end, so I just wanted to check that they haven't be resaved removing the CR. Can you see if the textfiles containt CR/LF or just LF? Maybe this is related to git and line ending. Just a theory.

**Comment by JanKallman** [comment]
In that case I'll remove the CR to avoid this problem,

**Comment by StevenKung** [comment]
I found that the problem may cause from ZIP.
I downloaded by git clone it does not occur,
but I used "Download ZIP" it will throw that exception.

**Comment by JanKallman** [comment]
Great, I'll remove the CR to avoid this problem in the future. Thanks for reporting this issue.
