### ISSUE TITLE
Add picture in a specific cell

### ISSUE THREAD

**Issue by StevenKung** [EPPlusSoftware/EPPlus.Sample.NetFramework#2]
about ShapesAndImagesSample
how to add a picture in a specific cell?  and resize when rows and colum are resized?
thanks

**Comment by JanKallman** [comment]
https://github.com/EPPlusSoftware/EPPlus.Sample.NetFramework/blob/5842e604ad670b66a695ef8abf42d402446a0d9d/14-ShapesAndImages/ShapesAndImagesSample.cs#L61 
sets the position. 
https://github.com/EPPlusSoftware/EPPlus.Sample.NetFramework/blob/5842e604ad670b66a695ef8abf42d402446a0d9d/14-ShapesAndImages/ShapesAndImagesSample.cs#L62 
Sets how the image is resized

**Comment by StevenKung** [comment]
If the picture is larger than cell width or height that make picture exceed a cell area.

**Comment by JanKallman** [comment]
You can use the pic.From and pic.Size property (if EditAs is OneCell) to set the position and size.
