### ISSUE TITLE
How add a few chart in loop

### ISSUE THREAD

**Issue by zaspany1** [EPPlusSoftware/EPPlus.Sample.NetFramework#4]
How add few charts in array?
 for (int x = 1; x < 5; x++)
                {
 var chart = worksheet.Drawings.AddChart(x, OfficeOpenXml.Drawing.Chart.eChartType.ColumnClustered);
                    chart.Title.Text = "Total";
                    chart.SetPosition(x, 1,x , 1);
                    chart.SetSize(100, 100);
                    worksheet.Cells[wiersz, 14, wiersz + 1, 25].Style.Fill.PatternType = ExcelFillStyle.Solid;
             
}

or is possible solution like this:
Sheet[1].Cells["A1"].Value = "Hello World!";

Or

pieChart[2].SetPosition(1, 0, 2, 0);
pieChart[2].SetSize(400, 400);

**Comment by JanKallman** [comment]
I'm unsure what the question is?
